name: Create inavdash-lua-ethos ZIP on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set build variables (PR version)
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "GIT_VER=PR-${PR_NUMBER}" >> $GITHUB_ENV

    - name: Update version and config in main.lua
      run: |
        # Use GIT_VER set in previous step
        sed -i 's/\(config.version = {[^}]*suffix = \)"[^"]*"/\1"${{ env.GIT_VER }}"/' scripts/inav-dashboard/main.lua

        # Set logging settings
        sed -i 's/\(config.logLevel= \)".*"/\1"off"/' scripts/inav-dashboard/main.lua
        sed -i 's/\(config.logToFile = \)[^ ]*/\1false/' scripts/inav-dashboard/main.lua
        sed -i 's/\(config.logMSP = \)[^ ]*/\1false/' scripts/inav-dashboard/main.lua

        # Show updated file (for verification)
        grep 'config\.' scripts/inav-dashboard/main.lua

    - name: Create inav-dashboard-ethos-PR-<number>.zip (entire scripts folder)
      run: |
        zip -q -r -9 "inav-dashboard-ethos-${{ env.GIT_VER }}.zip" scripts

    - name: Upload inav-dashboard-ethos-PR-<number>.zip as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: inav-dashboard-ethos-${{ env.GIT_VER }}
        path: inav-dashboard-ethos-${{ env.GIT_VER }}.zip
        if-no-files-found: error